// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentManagment.Data;

#nullable disable

namespace StudentManagment.Migrations
{
    [DbContext(typeof(SchoolContext))]
    [Migration("20251215103034_initialMigrations")]
    partial class initialMigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("StudentManagment.Models.CafeAccess", b =>
                {
                    b.Property<int>("CafeAccessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("HasAccessedBreakfast")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("HasAccessedDinner")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("HasAccessedLunch")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastResetDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ScannableIdCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("TotalDailyAccesses")
                        .HasColumnType("int");

                    b.HasKey("CafeAccessId");

                    b.HasIndex("ScannableIdCode")
                        .IsUnique();

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.ToTable("CafeAccesses");

                    b.HasData(
                        new
                        {
                            CafeAccessId = 1,
                            HasAccessedBreakfast = false,
                            HasAccessedDinner = false,
                            HasAccessedLunch = false,
                            LastResetDate = new DateTime(2025, 12, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ScannableIdCode = "8C:3C:CE:44",
                            StudentId = 1,
                            TotalDailyAccesses = 0
                        },
                        new
                        {
                            CafeAccessId = 2,
                            HasAccessedBreakfast = false,
                            HasAccessedDinner = false,
                            HasAccessedLunch = false,
                            LastResetDate = new DateTime(2025, 12, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ScannableIdCode = "F9:CE:D9:9B",
                            StudentId = 2,
                            TotalDailyAccesses = 0
                        },
                        new
                        {
                            CafeAccessId = 3,
                            HasAccessedBreakfast = false,
                            HasAccessedDinner = false,
                            HasAccessedLunch = false,
                            LastResetDate = new DateTime(2025, 12, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ScannableIdCode = "C6:65:D3:EA",
                            StudentId = 3,
                            TotalDailyAccesses = 0
                        },
                        new
                        {
                            CafeAccessId = 4,
                            HasAccessedBreakfast = false,
                            HasAccessedDinner = false,
                            HasAccessedLunch = false,
                            LastResetDate = new DateTime(2025, 12, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ScannableIdCode = "79:68:DB:9B",
                            StudentId = 4,
                            TotalDailyAccesses = 0
                        },
                        new
                        {
                            CafeAccessId = 5,
                            HasAccessedBreakfast = false,
                            HasAccessedDinner = false,
                            HasAccessedLunch = false,
                            LastResetDate = new DateTime(2025, 12, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ScannableIdCode = "67:EC:4B:84",
                            StudentId = 5,
                            TotalDailyAccesses = 0
                        },
                        new
                        {
                            CafeAccessId = 6,
                            HasAccessedBreakfast = false,
                            HasAccessedDinner = false,
                            HasAccessedLunch = false,
                            LastResetDate = new DateTime(2025, 12, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ScannableIdCode = "59:3B:3D:41",
                            StudentId = 6,
                            TotalDailyAccesses = 0
                        },
                        new
                        {
                            CafeAccessId = 7,
                            HasAccessedBreakfast = false,
                            HasAccessedDinner = false,
                            HasAccessedLunch = false,
                            LastResetDate = new DateTime(2025, 12, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ScannableIdCode = "55:03:FE:EC",
                            StudentId = 7,
                            TotalDailyAccesses = 0
                        });
                });

            modelBuilder.Entity("StudentManagment.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("CourseId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("DepartmentId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            Code = "CS101",
                            Credits = 3,
                            DepartmentId = 1,
                            IsActive = true,
                            Title = "Introduction to Programming"
                        },
                        new
                        {
                            CourseId = 2,
                            Code = "CS201",
                            Credits = 4,
                            DepartmentId = 1,
                            IsActive = true,
                            Title = "Data Structures"
                        },
                        new
                        {
                            CourseId = 3,
                            Code = "CS301",
                            Credits = 4,
                            DepartmentId = 1,
                            IsActive = true,
                            Title = "Algorithms"
                        },
                        new
                        {
                            CourseId = 4,
                            Code = "MATH101",
                            Credits = 3,
                            DepartmentId = 2,
                            IsActive = true,
                            Title = "Calculus I"
                        },
                        new
                        {
                            CourseId = 5,
                            Code = "MATH201",
                            Credits = 3,
                            DepartmentId = 2,
                            IsActive = true,
                            Title = "Linear Algebra"
                        },
                        new
                        {
                            CourseId = 6,
                            Code = "ENG101",
                            Credits = 3,
                            DepartmentId = 3,
                            IsActive = true,
                            Title = "English Composition"
                        },
                        new
                        {
                            CourseId = 7,
                            Code = "PHY101",
                            Credits = 4,
                            DepartmentId = 4,
                            IsActive = true,
                            Title = "Physics I"
                        },
                        new
                        {
                            CourseId = 8,
                            Code = "BUS101",
                            Credits = 3,
                            DepartmentId = 5,
                            IsActive = true,
                            Title = "Introduction to Business"
                        });
                });

            modelBuilder.Entity("StudentManagment.Models.CourseAssignment", b =>
                {
                    b.Property<int>("CourseAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("Semester")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("CourseAssignmentId");

                    b.HasIndex("CourseId");

                    b.HasIndex("TeacherId");

                    b.ToTable("CourseAssignments");

                    b.HasData(
                        new
                        {
                            CourseAssignmentId = 1,
                            CourseId = 1,
                            Semester = 0,
                            TeacherId = 1,
                            Year = 2024
                        },
                        new
                        {
                            CourseAssignmentId = 2,
                            CourseId = 2,
                            Semester = 0,
                            TeacherId = 1,
                            Year = 2024
                        },
                        new
                        {
                            CourseAssignmentId = 3,
                            CourseId = 3,
                            Semester = 1,
                            TeacherId = 1,
                            Year = 2024
                        },
                        new
                        {
                            CourseAssignmentId = 4,
                            CourseId = 4,
                            Semester = 0,
                            TeacherId = 2,
                            Year = 2024
                        },
                        new
                        {
                            CourseAssignmentId = 5,
                            CourseId = 5,
                            Semester = 1,
                            TeacherId = 2,
                            Year = 2024
                        });
                });

            modelBuilder.Entity("StudentManagment.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            IsActive = true,
                            Name = "Computer Science"
                        },
                        new
                        {
                            DepartmentId = 2,
                            IsActive = true,
                            Name = "Applied Mathematics"
                        },
                        new
                        {
                            DepartmentId = 3,
                            IsActive = true,
                            Name = "English Literature"
                        },
                        new
                        {
                            DepartmentId = 4,
                            IsActive = true,
                            Name = "Physics"
                        },
                        new
                        {
                            DepartmentId = 5,
                            IsActive = true,
                            Name = "Business Administration"
                        });
                });

            modelBuilder.Entity("StudentManagment.Models.Enrollment", b =>
                {
                    b.Property<int>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("Grade")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("EnrollmentId");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId", "CourseId", "Year", "Semester")
                        .IsUnique();

                    b.ToTable("Enrollments");

                    b.HasData(
                        new
                        {
                            EnrollmentId = 1,
                            CourseId = 1,
                            Grade = "A",
                            Semester = "Semester1",
                            StudentId = 1,
                            Year = 2024
                        },
                        new
                        {
                            EnrollmentId = 2,
                            CourseId = 2,
                            Grade = "B+",
                            Semester = "Semester1",
                            StudentId = 1,
                            Year = 2024
                        },
                        new
                        {
                            EnrollmentId = 3,
                            CourseId = 1,
                            Grade = "A-",
                            Semester = "Semester1",
                            StudentId = 2,
                            Year = 2024
                        },
                        new
                        {
                            EnrollmentId = 4,
                            CourseId = 4,
                            Grade = "B",
                            Semester = "Semester1",
                            StudentId = 3,
                            Year = 2024
                        },
                        new
                        {
                            EnrollmentId = 5,
                            CourseId = 6,
                            Grade = "A",
                            Semester = "Semester1",
                            StudentId = 4,
                            Year = 2024
                        },
                        new
                        {
                            EnrollmentId = 6,
                            CourseId = 1,
                            Grade = "A",
                            Semester = "Semester1",
                            StudentId = 7,
                            Year = 2024
                        });
                });

            modelBuilder.Entity("StudentManagment.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AccountNumber")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EnrollmentDate")
                        .HasColumnType("date");

                    b.Property<double>("GPA")
                        .HasColumnType("double");

                    b.Property<bool>("IsEnrolled")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ReceivesCashAllowance")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("StudentId");

                    b.HasIndex("AccountNumber")
                        .IsUnique();

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            DepartmentId = 1,
                            EnrollmentDate = new DateOnly(2021, 9, 1),
                            GPA = 3.5,
                            IsEnrolled = true,
                            ReceivesCashAllowance = false,
                            UserId = 3
                        },
                        new
                        {
                            StudentId = 2,
                            DepartmentId = 1,
                            EnrollmentDate = new DateOnly(2021, 9, 1),
                            GPA = 3.7999999999999998,
                            IsEnrolled = true,
                            ReceivesCashAllowance = false,
                            UserId = 4
                        },
                        new
                        {
                            StudentId = 3,
                            DepartmentId = 2,
                            EnrollmentDate = new DateOnly(2022, 9, 1),
                            GPA = 3.2000000000000002,
                            IsEnrolled = true,
                            ReceivesCashAllowance = false,
                            UserId = 5
                        },
                        new
                        {
                            StudentId = 4,
                            DepartmentId = 3,
                            EnrollmentDate = new DateOnly(2022, 9, 1),
                            GPA = 3.8999999999999999,
                            IsEnrolled = true,
                            ReceivesCashAllowance = false,
                            UserId = 6
                        },
                        new
                        {
                            StudentId = 5,
                            DepartmentId = 4,
                            EnrollmentDate = new DateOnly(2023, 9, 1),
                            GPA = 3.6000000000000001,
                            IsEnrolled = true,
                            ReceivesCashAllowance = false,
                            UserId = 7
                        },
                        new
                        {
                            StudentId = 6,
                            DepartmentId = 5,
                            EnrollmentDate = new DateOnly(2023, 9, 1),
                            GPA = 3.3999999999999999,
                            IsEnrolled = true,
                            ReceivesCashAllowance = false,
                            UserId = 8
                        },
                        new
                        {
                            StudentId = 7,
                            DepartmentId = 1,
                            EnrollmentDate = new DateOnly(2021, 9, 1),
                            GPA = 3.7000000000000002,
                            IsEnrolled = true,
                            ReceivesCashAllowance = false,
                            UserId = 9
                        });
                });

            modelBuilder.Entity("StudentManagment.Models.Teacher", b =>
                {
                    b.Property<int>("TeacherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("HireDate")
                        .HasColumnType("date");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("TeacherId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            TeacherId = 1,
                            DepartmentId = 1,
                            HireDate = new DateOnly(2010, 8, 1),
                            UserId = 2
                        },
                        new
                        {
                            TeacherId = 2,
                            DepartmentId = 2,
                            HireDate = new DateOnly(2015, 1, 15),
                            UserId = 10
                        });
                });

            modelBuilder.Entity("StudentManagment.Models.TeacherDepartmentHistory", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("HistoryId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("TeacherId");

                    b.ToTable("TeacherDepartmentHistory");
                });

            modelBuilder.Entity("StudentManagment.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1980, 1, 1),
                            Email = "admin@school.edu",
                            FirstName = "System",
                            Gender = "Male",
                            IsActive = true,
                            LastName = "Admin",
                            PasswordHash = "$2a$11$KLk9ZOo5rPwRL8rVqVUS.uLbsVbzYvwynCOChUyQhpnpseuUOU19G",
                            Phone = "1234567890",
                            Role = "Admin",
                            Username = "sys.admin"
                        },
                        new
                        {
                            UserId = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1985, 5, 20),
                            Email = "alice.smith@school.edu",
                            FirstName = "Alice",
                            Gender = "Female",
                            IsActive = true,
                            LastName = "Smith",
                            PasswordHash = "$2a$11$pUwviYr0BkvXxrccs3Mz2enXLP582dNuxCvSngXbE5viRlF/SVhMC",
                            Phone = "0987654321",
                            Role = "Teacher",
                            Username = "a.smith"
                        },
                        new
                        {
                            UserId = 10,
                            CreatedAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1978, 3, 15),
                            Email = "robert.chen@school.edu",
                            FirstName = "Robert",
                            Gender = "Male",
                            IsActive = true,
                            LastName = "Chen",
                            PasswordHash = "$2a$11$pUwviYr0BkvXxrccs3Mz2enXLP582dNuxCvSngXbE5viRlF/SVhMC",
                            Phone = "5551234567",
                            Role = "Teacher",
                            Username = "r.chen"
                        },
                        new
                        {
                            UserId = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(2002, 9, 15),
                            Email = "bob.johnson@school.edu",
                            FirstName = "Bob",
                            Gender = "Male",
                            IsActive = true,
                            LastName = "Johnson",
                            PasswordHash = "$2a$11$IhfNpX72Ez.nqaceXgE5xepe75j6x5LCUIRdWo7jlVAdlGmMsGSNO",
                            Phone = "1122334455",
                            Role = "Student",
                            Username = "b.johnson"
                        },
                        new
                        {
                            UserId = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(2003, 2, 28),
                            Email = "sarah.williams@school.edu",
                            FirstName = "Sarah",
                            Gender = "Female",
                            IsActive = true,
                            LastName = "Williams",
                            PasswordHash = "$2a$11$IhfNpX72Ez.nqaceXgE5xepe75j6x5LCUIRdWo7jlVAdlGmMsGSNO",
                            Phone = "2233445566",
                            Role = "Student",
                            Username = "s.williams"
                        },
                        new
                        {
                            UserId = 5,
                            CreatedAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(2002, 7, 10),
                            Email = "michael.brown@school.edu",
                            FirstName = "Michael",
                            Gender = "Male",
                            IsActive = true,
                            LastName = "Brown",
                            PasswordHash = "$2a$11$IhfNpX72Ez.nqaceXgE5xepe75j6x5LCUIRdWo7jlVAdlGmMsGSNO",
                            Phone = "3344556677",
                            Role = "Student",
                            Username = "m.brown"
                        },
                        new
                        {
                            UserId = 6,
                            CreatedAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(2003, 11, 5),
                            Email = "emma.davis@school.edu",
                            FirstName = "Emma",
                            Gender = "Female",
                            IsActive = true,
                            LastName = "Davis",
                            PasswordHash = "$2a$11$IhfNpX72Ez.nqaceXgE5xepe75j6x5LCUIRdWo7jlVAdlGmMsGSNO",
                            Phone = "4455667788",
                            Role = "Student",
                            Username = "e.davis"
                        },
                        new
                        {
                            UserId = 7,
                            CreatedAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(2002, 4, 22),
                            Email = "james.miller@school.edu",
                            FirstName = "James",
                            Gender = "Male",
                            IsActive = true,
                            LastName = "Miller",
                            PasswordHash = "$2a$11$IhfNpX72Ez.nqaceXgE5xepe75j6x5LCUIRdWo7jlVAdlGmMsGSNO",
                            Phone = "5566778899",
                            Role = "Student",
                            Username = "j.miller"
                        },
                        new
                        {
                            UserId = 8,
                            CreatedAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(2003, 8, 30),
                            Email = "olivia.wilson@school.edu",
                            FirstName = "Olivia",
                            Gender = "Female",
                            IsActive = true,
                            LastName = "Wilson",
                            PasswordHash = "$2a$11$IhfNpX72Ez.nqaceXgE5xepe75j6x5LCUIRdWo7jlVAdlGmMsGSNO",
                            Phone = "6677889900",
                            Role = "Student",
                            Username = "o.wilson"
                        },
                        new
                        {
                            UserId = 9,
                            CreatedAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(2002, 12, 18),
                            Email = "david.taylor@school.edu",
                            FirstName = "David",
                            Gender = "Male",
                            IsActive = true,
                            LastName = "Taylor",
                            PasswordHash = "$2a$11$IhfNpX72Ez.nqaceXgE5xepe75j6x5LCUIRdWo7jlVAdlGmMsGSNO",
                            Phone = "7788990011",
                            Role = "Student",
                            Username = "d.taylor"
                        });
                });

            modelBuilder.Entity("StudentManagment.Models.CafeAccess", b =>
                {
                    b.HasOne("StudentManagment.Models.Student", "Student")
                        .WithOne("CafeAccess")
                        .HasForeignKey("StudentManagment.Models.CafeAccess", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentManagment.Models.Course", b =>
                {
                    b.HasOne("StudentManagment.Models.Department", "Department")
                        .WithMany("Courses")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("StudentManagment.Models.CourseAssignment", b =>
                {
                    b.HasOne("StudentManagment.Models.Course", "Course")
                        .WithMany("CourseAssignments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManagment.Models.Teacher", "Teacher")
                        .WithMany("CourseAssignments")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("StudentManagment.Models.Enrollment", b =>
                {
                    b.HasOne("StudentManagment.Models.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManagment.Models.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentManagment.Models.Student", b =>
                {
                    b.HasOne("StudentManagment.Models.Department", "Department")
                        .WithMany("Students")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudentManagment.Models.User", "User")
                        .WithOne("Student")
                        .HasForeignKey("StudentManagment.Models.Student", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudentManagment.Models.Teacher", b =>
                {
                    b.HasOne("StudentManagment.Models.Department", "Department")
                        .WithMany("Teachers")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StudentManagment.Models.User", "User")
                        .WithOne("Teacher")
                        .HasForeignKey("StudentManagment.Models.Teacher", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudentManagment.Models.TeacherDepartmentHistory", b =>
                {
                    b.HasOne("StudentManagment.Models.Department", "Department")
                        .WithMany("TeacherHistoryLinks")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManagment.Models.Teacher", "Teacher")
                        .WithMany("DepartmentHistory")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("StudentManagment.Models.Course", b =>
                {
                    b.Navigation("CourseAssignments");

                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("StudentManagment.Models.Department", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Students");

                    b.Navigation("TeacherHistoryLinks");

                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("StudentManagment.Models.Student", b =>
                {
                    b.Navigation("CafeAccess");

                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("StudentManagment.Models.Teacher", b =>
                {
                    b.Navigation("CourseAssignments");

                    b.Navigation("DepartmentHistory");
                });

            modelBuilder.Entity("StudentManagment.Models.User", b =>
                {
                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });
#pragma warning restore 612, 618
        }
    }
}
